### ISSUE TITLE
[Error] Plugin gets disabled when using Bungee + MySQL database

### ISSUE THREAD

**Issue by TH3N3WN00B** [MiloszBratkowski/HelpOPTB#2]
Error:

https://paste.gg/p/anonymous/f860b49f200040b5b4b4cf5d56a75344

**Comment by MiloszBratkowski** [comment]
This error is due to incorrect sql syntax for your database. Can you please provide more information: spigot version, bungeecord version, your database version and database engine.
I can't get these errors on my db and spigot.

**Comment by TH3N3WN00B** [comment]
Sorry, im not using the plugin anymore, forgot to close this issue, thanks for the reply tho...
